### ISSUE TITLE
Fix wasabi 403 error

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#160]
Debug the Forbidden HTTP error on wasabi upload calls and solve it

Acceptance criteria
1 - Flutter SDK tests working with wasabi calls

**Comment by mike-audi** [comment]
![Image](https://user-images.githubusercontent.com/3769672/201596381-c8df58eb-6a15-4248-acf9-de19c4bd5582.png)


NOTE: Flutter Base64Url adds unsafe padding (=) char which can mess with aiddresses (b64url(sha3(pubKey)). To be safe I added `address = address.replaceAll("=", '');` after encoding. We probably need to apply this in the backup service and/or node service for consistency.
