### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#163]

**Comment by mike-audi** [comment]
notes to self for tweaks: 

- we should get @Vigneshsanath to design us a proper readme header image
- we need a better/different intro 
- getting started first line of text is confusing
- fix odd text capitalization
- the api reference content should move into api docs
- we should include a simple explanation on how it works/basic architecture
- we should include where to go for help, docs, etc.

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/203335868-12dcfb07-e39e-433f-8607-a56daadf25ab.png)
