### ISSUE TITLE
Force tests to pass before deploying

### ISSUE THREAD

**Issue by mike-audi** [tiki/tiki-sdk-dart#164]
Code is deployed on release even if tests are failing. 
Forcing tests to pass before release will cut down on sloppy releases. 

requirements:
- add a test check step to deployment action

**Comment by ricardobrg** [comment]
It will be better handled in #169 but I already added the tests step in release action

![Image](https://user-images.githubusercontent.com/8357343/202227259-1a09c0f5-7811-4537-abec-764c44c20ef6.png)
