### ISSUE TITLE
Improve error handling for duplicate transaction Ids

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#215]
When calling a Consent or Ownership creation method with the same parameters, the Node throws a generic SQLite error of duplicate transaction id. The message should be improved to simplify the debugging.

The NodeService should catch duplicate transaction id errors and throw a new type of exception: DuplicateTxnIdException

Acceptance criteria
1 - NodeService throws DuplicateTxnIdException
2 - Unit tests

**Comment by mike-audi** [comment]
We also need to expose an authorization exception for registry errors.
