### ISSUE TITLE
Rename "source" to "ptr" in Ownership

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#220]
As proposed in #203, in OwnershipModel change the parameter "source" to "asset".

For backward compatibilty, keep a getter/setter "source" that will get/set the "asset" parameter and add deprecation notice.

Acceptance criteria:
1 - All parameters names changed and tests passes.

**Comment by mike-audi** [comment]
instead of asset, the name should be ptr as in Pointer Record.
