### ISSUE TITLE
Remove data type 

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#221]
As proposed in https://github.com/tiki/tiki-sdk-dart/issues/203, the data type 'pool' needs to be renamed to 'collection'.

For backward compatibilty, keep a getter "pool" that will return the 'collection' enum.

Acceptance criteria:
1 - All names changed and tests passes.

**Comment by mike-audi** [comment]
Instead of adjusting this enum, we're going to remove it entirely.
