### ISSUE TITLE
Naming changes

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#222]
Moving this here from #203 for further discussion

- rename `Ownership` to `Title`
- rename `Consent` to `License`
- Exposed models should not be prefixed with `TikiSdk`
- The `TikiSdkOwnership` object should be renamed to `DataTitle`
- The `TikiSdkConsent` object should be renamed to `DataLicense` 
- `TikiSdkDataTypeEnum` should be `DataType` with enums of `POINT`, `COLLECTION`, `STREAM`

**Comment by ricardobrg** [comment]
These should be treated after the naming changes:
- getOwnership should become getTitle and return the title object, which can be modified and saved
- getConsent should become getLicense and return the license object, which can be modified and saved. The license object should have the TitleObject in it, not just the identifier.

**Comment by mike-audi** [comment]
Only do this:

- rename `Ownership` to `Title`
- rename `Consent` to `License`
- Exposed models should not be prefixed with `TikiSdk`
