### ISSUE TITLE
Take "uses" and "paths" out of TikiSdkDestination

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#225]
The Consent NFT should have "uses" and "destinations" parameters. These should replace TikiSdkDestination functionality, where paths are moved to destinations.

For backward compatibility, TikiSdkDestination should be deprecated and pass its values to/from the new parameters.

Acceptance criteria
1 - Class parameters updated
2 - Tests for new parameters and backward compatibility (old tests should pass)

**Comment by mike-audi** [comment]
Follow spec here: https://docs.mytiki.com/docs/specifying-terms-and-usage
