### ISSUE TITLE
Change `reward` in Consent to `compensation`

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#226]
As proposed in https://github.com/tiki/tiki-sdk-dart/issues/203, in ConsentModel change the parameter "reward" to "compensation".

For backward compatibilty, keep a getter/setter "compensation" that will get/set the "reward" parameter and add deprecation notice.

Acceptance criteria:
1 - All parameters names changed and tests passes.

**Comment by mike-audi** [comment]
replaced by #224
