### ISSUE TITLE
Add user_id parameter to the SDK

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-dart#227]
From #203:

init(...) should instead of taking an address take a user_id as a parameter. We should store the address to user_id mapping locally and open the wallet, if it exists. If not, it we create a new wallet and map it. The address, user_id, and public_key should be publicly available via get methods. The init method should return this for 1-line instantiations.

**Comment by mike-audi** [comment]
closing in favor of #269
