### ISSUE TITLE
Use conditional imports OR move FFI bits out of core sdk

### ISSUE THREAD

**Issue by jcockhren** [tiki/tiki-sdk-dart#263]
When compiling for web clients, we cannot use Dart libraries that use `dart:ffi` as a dependency; therefore, we should exclude it from builds (e.g., [tiki-sdk-js](https://github.com/tiki/tiki-sdk-js)).

### Option 1: Conditional Imports

In Dart 2, support for custom flags was removed. Support for flags for dart internal libraries remains an **undocumented** feature.  dart-lang/sdk#34262. 

#### Cons

- More dependencies of this project that may be experimental and untested.
- There is no indication of whether the conditional import pattern will work in Dart 3.

### Option 2: Remove `dart:ffi` specific bits from the core SDK

Another option is to remove `dart:ffi` based implementations from the core SDK altogether.

#### Cons

- Requires update to flutter SDK because a lot of it is _for_ flutter, I think.
- A lot more work

### Option 3: Refactor import statements

Refactoring the imports to be less spaghetti-like could make it easy to outright _avoid_ `dart:ffi` & friends.

#### Cons:

- We'll have to re-implement key parts of the interface so that we only tap into the classes we want
- We may find that we still need to do conditional imports or move FFI bits out

**Comment by ricardobrg** [comment]
@jcockhren did you check the [sqlite3 web support](https://pub.dev/packages/sqlite3#wasm-web-support)?

**Comment by jcockhren** [comment]
> @jcockhren did you check the [sqlite3 web support](https://pub.dev/packages/sqlite3#wasm-web-support)?

Yes. I saw that sqlite3 is possible with WASM. This is a result of findings with `@staticInterop` related things since it's the [documented way to go](https://pub.dev/packages/js#static-interop) and has compatibility with WASM.

We're exploring both WASM and not WASM ways do doing things.

**Comment by jcockhren** [comment]
With #265, I did a combination of options 1 and 2. Moving from `Database` to `CommonDatabase` keeps the core SDK implementation from depending on FFI bits by letting downstream libraries choose the concrete class that works best in their platform.

**Comment by mike-audi** [comment]
@jcockhren, with your changes merged in, is this story complete?
